# Generated by Django 3.2.13 on 2022-06-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='Image_Set_1',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='Image_Set_2',
        ),
    ]
